- schemas/system_profile/v1.yaml
The $id key is not compatible with OpenAPI. Remove it.
In https://github.com/RedHatInsights/insights-host-inventory/pull/682, an exact copy of this file starts to be used in the OpenAPI specification. Syncing.
Hopefully the _$id_ won’t be necessary to use _jsonschema_ or other libraries directly.
> Remove $id

- schemas/system_profile/v1.yaml
without this some tools (e.g. linters) may not recognize this as a JSON Schema
> add schema to this schema

- schemas/system_profile/v1.yaml
Copied string length constraints from Marshmallow [models](https://github.com/RedHatInsights/insights-host-inventory/blob/4c97acb7cf77d4181db9fbc2a574b4a3759987d2/app/models.py) to the externalized schema. Now the validation rules here match those in Marshmallow.
JIRA ticket [RHCLOUD-7497](https://projects.engineering.redhat.com/browse/RHCLOUD-7497)
> Copy string length constraints from Marshmallow

- schemas/system_profile/v1.yaml
- The titles don’t add any value. They just repeat what the names say. Removed.
- Definitions with schemas are objects by default. Use object only for arbitrary dictionaries. (Those are going to be removed anyway.)
- Version is not necessary. For now there is going to be only one canonical schema.
No JIRA ticket. Slightly related to [RHCLOUD-8147](https://projects.engineering.redhat.com/browse/RHCLOUD-8147).
> Remove unnecessary stuff

- tools/simple-test/tester.py
Turned the JSON Schema tester to a proper standalone script:
- Used argparse to parse command line arguments.
- Added `__name__ == "__main__"` conditional to make it importable.
- Chmodded u+x to make it executable.
_run.sh_ still works without change.
Possible usage:
```bash
$ . tools/simple-test/venv/activate
$ tools/simple-test/tester.py ../../schemas/system_profile/v1.yaml ../../scratch/sample.json
```
> Make tester executable

- schemas/system_profile/v1.yaml
Added a constraint for _/disk_devices/options_. In Marshmallow we require all keys to be non-empty strings, including those of the nested objects. The new constraint does exactly this.
Examples of invalid payloads:
```json
"disk_devices": [
{
"type": "ext3",
"label": "home drive",
"device": "/dev/sdb1",
"options": {
"ro": true,
"uid": "0",
"": "thou shall not pass"
},
"mount_point": "/home"
}
],
```
```json
"disk_devices": [
{
"type": "ext3",
"label": "home drive",
"device": "/dev/sdb1",
"options": {
"ro": true,
"uid": "0",
"nested": {
"this": "is fine",
"": "is not"
}
},
"mount_point": "/home"
}
],
```
> Disk device options

- schemas/system_profile/v1.yaml
Downgraded the JSON Schema to the Draft 7 version. It is the most recent version supported by _jsonschema 3.2.0_ used by the Inventory. [[Reference](https://github.com/Julian/jsonschema/tree/v3.2.0#features)] This version is automatically determined and used both by the Spectral linter and by the tester script. We need at least version 6 because of the _propertyNames_ support. The same JSON Schema version is going to be used in the Inventory.
To test this:
1. Run the linter
```bash
$ spectral lint schemas/system_profile/v1.yaml`.
```
2. See that the correct version has been detected.
```
JSON Schema Draft 7 detected
```
3. Create a sample JSON file that is invalid only against Draft 7.
```json
{
"disk_devices": [
{
"options": {
"": "empty key"
}
}
]
}
```
4. Run the tester script.
```bash …
```
> Change schema version to Draft7

- schemas/system_profile/v1.yaml
I was wrong in #7 claiming that there is no need to explicitly define object types.
If there is no type defined, any type is valid. In case of objects, defining properties and stuff is not enough. Those are used only if the respective document is an object, but non-objects are still valid. Added explicit type definitions to all objects.
This also helps Connexion’s _coerce_type_ function to correctly process values of an object. The function is going to be used in the Host Inventory.
```python
from jsonschema import validate
schema = {"properties": {"property": {"minLength": 1}}}
validate({"property": ""}, schema)  # invalid
validate([""], schema)  # valid
```
> Make objects explicit again

- .spectral.yaml
- schemas/system_profile/v1.yaml
By a mistake, the _yum_repos/base_url_ key had a wrong name. @rodrigonull reported this. Unfortunately this even got to the Host Inventory codebase, causing this value not to be stored at all. 😞 A fix for this in the Host Inventory is a part of https://github.com/RedHatInsights/insights-host-inventory/pull/715. Fixing here too for consistency.
> Fix yum_repos/base_url field name

- .spectral.yaml
- schemas/system_profile/v1.yaml
I think the current `NestedObject` definition is that all the children of `options` must be objects. For example, a valid request is expected to look like the following: `options: {"uid": {"blah: {"another_one": {}}}}`. 
But, I think what we want `options` to look like is something like this: `options: {"uid":"0","ro":false, "random":{"yep":true}}`.
We can close/update this if this isn't accurate. :+1: 
Corresponding HBI PR: https://github.com/RedHatInsights/insights-host-inventory/pull/771
> Fixing NestedObject definition

- schemas/system_profile/v1.yaml
OpenApi specification does not support `propertyNames`. Check [here](https://swagger.io/docs/specification/data-models/keywords/).
We will use a custom validator to treat `x-propertyNames` as `propertyNames`.
HBI PR that handles `x-propertyNames`: https://github.com/RedHatInsights/insights-host-inventory/pull/771
> Use x-propertyNames in place of propertyNames

- schemas/system_profile/v1.yaml
Even though SAP installs cannot have 98 or 99 as their instance number, these are valid coming from diagnostic tools so we need to relax our schema to allow these values.
https://issues.redhat.com/browse/HBISPSC-37
> Relax sap_instance_number to include 98/99

- schemas/system_profile/v1.yaml
A way to have all packages passed along and not only the max of multi values provided by installed_packages without breaking those dependent on the current implementation of installed_packages.
Dependent on:
https://github.com/RedHatInsights/insights-puptoo/pull/69
> Include all remaining packages not in installed_packages

- schemas/system_profile/v1.yaml
Trying to use a Draft 7 validator to validate system_profile in HBI is causing us some hurdles as I explained [here](https://github.com/RedHatInsights/insights-host-inventory/pull/771#issuecomment-756366770).
I found the draft 7 version of the schema that lives in this repo to be fully backward compatible with draft 4, and I don't think we will be needing those draft 7 features of the schema here (feel free to disagree). While trying to resolve the discrepancies, we found it to be simpler to use a draft 4 validator instead of a draft 7 one. Therefore, I am opening this PR to downgrade this to draft 4 for the sake of consistency. 
Links:
- [HBI PR](https://github.com/RedHatInsights/insights-host-inventory/pull/771)
- [Draft 4 -> Draft 6 …
> Downgrade schema from draft 7 to draft 4

- schemas/system_profile/v1.yaml
There is an apostrophe in a description that is throwing off some yaml
safe_load operations. Running into an encoding error.
This should fix that
Signed-off-by: Stephen Adams <tsadams@gmail.com>
> fix: apostrophe in system_profile schema

- schemas/system_profile/v1.yaml
support for subscription-manager release lock
reopening this PR once again as it was incorrecly closed (see #18).
os release and rhsm release are independent values.
you can install e.g. RHEL 8.3 and set RHSM to lock version to 8.2
> added rhsm_releasever

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
- tests/utils/valids.py
Add the cpu model name as cpu_model to system profile as requested:
https://issues.redhat.com/browse/HBISPSC-39
Related puptoo PR:
https://github.com/RedHatInsights/insights-puptoo/pull/117
> Add the model name as cpu_model to system profile

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
- tests/utils/valids.py
Addresses this Jira: https://issues.redhat.com/browse/RHCLOUD-12582
Adds the boolean "is_marketplace" field to the system profile.
The corresponding host-inventory PR is here: https://github.com/RedHatInsights/insights-host-inventory/pull/823
> Add is_marketplace boolean field to system profile

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
- tests/utils/valids.py
Addresses [this Jira](https://issues.redhat.com/browse/RHCLOUD-12722). This simply adds the `rhc_config_state` field to the system profile.
The corresponding HBI PR is [here](https://github.com/RedHatInsights/insights-host-inventory/pull/829).
> Add rhc-config-state field to SP

- .github/CODEOWNERS
Does a couple of things:
1. Updates the System Profile spec folder path to reference the specific folder that we update (from root, not just any folder matching that pattern)
2. Adds @CodeHeeler to the list of reviewers, since she's a stakeholder
I'm not sure why Stephen Adams keeps getting added as a reviewer to every PR, but nobody else we've listed (besides HBI team) gets added. I'm hoping that fixing the path will get it to work
> Update CODEOWNERS path and add codeheeler

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
Fixes https://issues.redhat.com/browse/HBISPSC-38
Turns out sestatus code allows a value like `error (X)"` where X is more info about the error.
This change allows the `selinux_config_file` field to contain any string up to 128 characters.
> Change selinux_config_file from enum to allow a string

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
- tests/utils/valids.py
GPG pubkeys are stored as an array of package names with RPM sorting applied.
The sort probably has no meaning for these synthetic packages, but it makes
order consistent.
Signed-off-by: Christopher Sams <csams@redhat.com>
> Add gpg_pubkey array

- package-lock.json
Addresses [RHCLOUD-13878](https://issues.redhat.com/browse/RHCLOUD-13878).
Updates `@stoplight/spectral` and its dependencies. This will hopefully fix the security vulnerabilities that dependabot seems unable to fix.
> Update spectral & dependencies

- schemas/system_profile/v1.yaml
Hey, small change that shouldn't efffect anything else. I run into parsing errors in the script I'm creating to automatically update the elasticsearch mapping in xjoin-search when SystemProfile doesn't have a title field. This PR simply gives it a title :)
> Fix parsing error in xjoin-search mapping updater

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
- tests/utils/valids.py
"123.456.789.012" is not a valid ipv4 address. I've updated our example values to use "192.0.2.146", which _is_ valid.
> Fix ipv4 address example

- schemas/system_profile/v1.yaml
Generic filtering for xjoin work has lead to some small changes in how the schema should be. I've updated the schema to be compliant and updated our instructions for contribution to include the new requirements.
The biggest change is the need to provide an example string with 3 different (unless that's impossible) example values for new string fields. This is so that we can automatically populate example hosts in xjoin-search with realistic data for manual and automated tests.
The requirements may still change as test generation work for generic filtering on xjoin is ongoing. Please let me know if there are any concerns around the changes or there are any better ways to insure compliance with the new requirements, especially the example strings.
> Generic filtering xjoin related changes

- .github/CODEOWNERS
Dana is now part of the @RedHatInsights/host-based-inventory-committers group, so this removes the explicit reference in the CODEOWNERS file.
> Remove codeheeler from CODEOWNERS

- README.md
- schemas/system_profile/v1.yaml
The examples provided need to be different values - specifically, the first and second values can't be the same. I've updated a couple of offending fields and updated the README to specify this criteria.
> Update examples; update README

- .github/workflows/pr.yml
- tests/test_schema.py
- tests/utils/invalids.py
- tests/utils/valids.py
These patches fix the following issue:
```
Error: Version 3.6 with arch x64 not found
```
Cause: there is no available build of Python 3.6 for ubuntu-22.04
ref: [Error: Version 3.6 with arch x64 not found](https://github.com/actions/setup-python/issues/544)
And also fixes the flake8 syntax errors.
Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>
> [ci] Fix Python3.6 issue on Linux x86

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
- tests/utils/valids.py
Adds hyperscaler public autogenerated DNS, only available on AWS EC2.
This is a followup for https://github.com/RedHatInsights/inventory-schemas/commit/a09c33520891022af77fd3e2fcaca46a9bf95bda
https://issues.redhat.com/browse/ESSNTL-4992
> Add cloud external DNS

- schemas/system_profile/v1.yaml
- tests/utils/valids.py
Currently, in the system_profile schema, under operating_system:properties:name the schema is defined for [RHEL, CentOS]. During a previous conversation it was mentioned that CentOS 7 systems need to say "CentOS Linux", and if we ever enabled CentOS Stream, that name would need added as well. With my proposed change to puptoo, systems fail to update/check in with the new functionality of the "CentOS Linux" name because the schema does not allow it.  I am proposing that we simply update that one name.
> RHINENG-1494 adding proposed changes to os name

- schemas/system_profile/v1.yaml
https://issues.redhat.com/browse/RHIN-1077
Generally speaking, this will be equal to:
```python
threads_per_core = number_of_cpus / (number_of_sockets * cores_per_socket)
```
However, given hypervisors can report inaccurate CPU topologies, this field will give us a way to indicate the real SMT ratio.
For example, a VM can be provisioned having the following apparent CPU topology:
```python
number_of_sockets = 5
number_of_cpus = 5
cores_per_socket = 1
```
This would suggest a `threads_per_core` value of `1`. However, the hypervisor could actually be a 3 core machine with an SMT ratio of 2.
Capturing `threads_per_core` separately allows us to capture these nuances, when tooling and reporters support this.
> RHIN-1077: Add threads_per_core

- schemas/system_profile/v1.yaml
virtual_host_uuid field is added to reflect the hypervisor identity (subiscription_manager_id) of a system's hypervisor (which is typically collected by virt-who).
https://issues.redhat.com/browse/DISCOVERY-325
> DISCOVERY-325: Add virtual_host_uuid

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
- tests/utils/valids.py
[RHINENG-7611 ](https://issues.redhat.com/browse/RHINENG-7611)
> RHINENG-7611: Add bootc_status

- schemas/system_profile/v1.yaml
This PR addresses [RHINENG-7729](https://issues.redhat.com/browse/RHINENG-7729). While trying to synchronize the change introduced with #123, we discovered that there's an issue in one of our dependencies that causes everything to break when a $ref is used outside the context of array.items.
I've opened [RHINENG-7731](https://issues.redhat.com/browse/RHINENG-7731) to address the above issue, and to remove the duplication once the issue is resolved.
Follows up on #123.
> fix(RHINENG-7729): Manually resolve $refs as a workaround

- schemas/system_profile/v1.yaml
Follows up on #122. HBI's validation code ran into issues with the original structure of this object, so I refactored the array items into their own schema in the `defs` section. When formatted this way, the validation works without error.
> FIX: Refactor array items into def section

- README.md
- schemas/system_profile/v1.yaml
Since we no longer use xjoin, x-indexed is no longer needed. This PR removes x-indexed from all fields, and removes the relevant info from the README.
Addresses [RHINENG-12590](https://issues.redhat.com/browse/RHINENG-12590).
> Remove x-indexed from fields

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
- tests/utils/valids.py
- add field `workloads.rhel_ai.ai_models`
- add field `workloads.rhel_ai.free_disk_storage`
- add field `workloads.rhel_ai.gpu_models`
- intro this new field to better describe the gpu_models info across diff vendors with attributes:
- `name`
- `vendor`
- `memory`
- `count` 
- and let it deprecate the recently added fields: (via https://github.com/RedHatInsights/inventory-schemas/pull/148)
- `nvidia_gpu_models`
- `amd_gpu_models`
- `intel_gaudi_hpu_models`
- Hope these `workloads.rhel_ai.*_gpu_models` fields are not referred by services except reporter puptoo. 
More details in RHINENG-15790
> RHINENG-15790: add facts to "workloads.rhel_ai" field

- schemas/system_profile/v1.yaml
- tests/utils/invalids.py
To align with the Puptoo "system_purpose" fact populating: https://github.com/RedHatInsights/insights-puptoo/pull/461
More details for the schema update reason in RHINENG-18525
> RHINENG-18525: drop the enum restriction for "system_purpose"

- schemas/system_profile/v1.yaml
This PR addresses [RHINENG-19793](https://issues.redhat.com/browse/RHINENG-19793). Adds the `x-dynamic` identifier to fields that are in the `system_profiles_dynamic` table. This will allow HBI to determine the correct table association for each field.
> chore(RHINENG-19793) Add x-dynamic to fields that will be in the dynamic table
