RedHatInsights/inventory-schemas

schemas/system_profile/v1.yaml

Do we want to do something more like this? instead of #26 and #9 
@jharting do you think flatter is better for searching
cc @gmcculloug on the searching thing

Combining #9 and #26 splitting os release and adding os vendor flavor etc

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

Subsequent HBI PR: https://github.com/RedHatInsights/insights-host-inventory/pull/892

Add field to identify edge hosts

---

tools/simple-test/requirements.txt

Updates the PyYAML dependency in requirements.txt to resolve a security vulnerability.

Use newer PyYAML for security reasons

---

schemas/system_profile/v1.yaml

Going through the schema with a fine tooth comb while working on generic filtering so I thought id put a PR for any little formatting things that bug me
It ended up just being literally one line I wanted to move :shrug: type is at the top everywhere else

Small nitpick change

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

Signed-off-by: Christopher Sams <csams@redhat.com>

Add greenboot fallback detected bool to system profile.

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

Addresses this implementation Jira: https://issues.redhat.com/browse/ESSNTL-600
Parent Jira: https://issues.redhat.com/browse/ESSNTL-578

Add system_purpose fields

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

This is another PR addressing [ESSNTL-600](https://issues.redhat.com/browse/ESSNTL-600). Ronny noted that these fields would make more sense on a combined object, so I went ahead and made that change.

Combine system_purpose fields into an object

---

schemas/system_profile/v1.yaml

Sets up wildcard filter support for Ansible workload fields.

Add wildcard support for Ansible workload fields

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

Create SAP object for consistency with other workloads and move existing SAP related fields to within it (sap_version, sap_system, sap_instance_number, and sap_sids if that one is not too complicated due to direct dependencies*).
*Included sap_sids in this draft, will reach out to folks and see what dependencies exist and how difficult they would be to resolve/time before merging this PR.

[ESSNTL-2678] Create SAP object

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

mirrorlist information would be needed for RHUI support.
VULN-2440

feat: add mirrorlist to YumRepo

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

This PR adds update_method to system_profile_schema, [ESSNTL_3575](https://issues.redhat.com/browse/ESSNTL-3575)

add update_method to system_profile schema

---

LICENSE.txt

This PR is being created to add a license file. Using GPLv2 to match with insights-hosts-inventory update.

Add GPLv2 license

---

schemas/system_profile/v1.yaml

[RHINENG-2402](https://issues.redhat.com/browse/RHINENG-2402)

RHINENG-2402 add failed services for systemd

---

README.md

+ adding [@koalakangaroo](https://github.com/koalakangaroo) into loop

update maintainer info for Yupana and Puptoo service

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

Resolve inventory-schema validation issue in [RHINENG-8752](https://issues.redhat.com/browse/RHINENG-8752)

Remove the RPMOSTreeDeployment origin minLength restriction

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

[SWATCH-2423](https://issues.redhat.com/browse/SWATCH-2423)

SWATCH-2423: Add "conversions" field to schema

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

Related Puptoo system_profile changes at https://github.com/RedHatInsights/insights-puptoo/pull/328

RHINENG-9246: update "bootc_status" field of schema

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

[RHINENG-11008](https://issues.redhat.com/browse/RHINENG-11008) 
Related Puptoo change PR: https://github.com/RedHatInsights/insights-puptoo/pull/343

RHINENG-11008: add "falcon_version" field to schema

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

[RHINENG-11774](https://issues.redhat.com/browse/RHINENG-11774)

RHINENG-11774: add "rhel_ai" field to schema

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

The related system_profile facts adding in Puptoo:  https://github.com/RedHatInsights/insights-puptoo/pull/404

RHINENG-14549: add rhel ai gpu model fields to schema

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

- include the existing workload objects
- add new workload "ibm_db2" and "oracle_db"

RHINENG-15724: add unified entry "workloads" field to schema

---

schemas/system_profile/v1.yaml
tests/utils/invalids.py
tests/utils/valids.py

Update `captured_date` field to be a date-time field.

update captured-date field to be datetime
